### ISSUE TITLE
Unable to select files from Google Drive

### ISSUE THREAD

**Issue by leachuk** [adobe/aem-sidekick#134]
### Expected Behaviour
I can use the Sidekick to select documents from my Google Drive to publish, as described in https://www.aem.live/developer/tutorial

### Actual Behaviour
The extension is installed and active. When documents are selected in Google Drive, they are not reflected in the Sidekick toolbar. It maintains the message "Select files below"

### Reproduce Scenario (including but not limited to)
I've tried this in Chrome, Chrome Incognito and Safari. The broken behaviour is consistent, so I do not believe there is some other extension or browser setting causing this (of course it's difficult to be 100% sure of this as there are no error messages provided)

#### Steps to Reproduce
Following the steps in the tutorial at https://www.aem.live/developer/tutorial

#### Platform and Version
MacOS Sonoma 14.4.1 (23E224)
Chrome Version 124.0.6367.93 (Official Build) (arm64)
Safari Version 17.4.1 (19618.1.15.11.14)

Chrome Sidekick 6.43.0 (Installed from Chrome extension store)

#### Logs taken while reproducing problem
I'll need some help to understand where to find any relevant logs.

**Comment by leachuk** [comment]
![Screenshot 2024-05-02 at 10 27 31 AM](https://github.com/adobe/aem-sidekick/assets/4289596/99af5df2-563c-4c56-a681-dbc9c2289140)

**Comment by leachuk** [comment]
Wait, does this belong in https://github.com/adobe/helix-sidekick-extension

You guys and your product names 😂

**Comment by leachuk** [comment]
Closing as I've opened in the correct repo. For anyone else who hits this https://github.com/adobe/helix-sidekick-extension/issues/724

**Comment by rofe** [comment]
@leachuk Thanks for reporting! We'll eventually port it here as well 😇
