### ISSUE TITLE
display correct icon for spreadsheets

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/aem-sidekick#173]
it would be great if the data view displayed a sheets (or excel) icon for `.json` resources.

<img width="615" alt="image" src="https://github.com/adobe/aem-sidekick/assets/5289336/dd88d32d-4cd7-4d9c-bab1-06d4d2f0d91f">

**Comment by rofe** [comment]
this has been fixed:
<img width="312" alt="image" src="https://github.com/adobe/aem-sidekick/assets/1609742/e6be9a38-d0a8-49ed-b0a6-dc36ca2ecaff">
