### ISSUE TITLE
Improve loading on static html pages

### ISSUE THREAD

**Issue by dylandepass** [adobe/aem-sidekick#175]
Couple issues, which may or may not be related to the content being a static html file.

1. Preview returns a 404 and we are not currently handling that situation correctly. 
2. The sidekick config call on the helix website does not return a mountpoint which we are also not expecting.

```
{
    "previewHost": "rum-admin--helix-website--adobe.aem.page",
    "liveHost": "rum-admin--helix-website--adobe.aem.live",
    "contentSourceUrl": "https://drive.google.com/drive/u/0/folders/18G2V_SZflhaBrSo_0fMYqhGaEF9Vetkz",
    "contentSourceType": "google",
    "host": "www.aem.live",
    "project": "Helix Website"
}
```

A typical response is

```
{
    "mountpoints": [
        "https://adobe-my.sharepoint.com/:f:/r/personal/dyland_adobe_com/Documents/helix-playground"
    ],
    "contentSourceUrl": "https://adobe-my.sharepoint.com/:f:/r/personal/dyland_adobe_com/Documents/helix-playground",
    "contentSourceType": "onedrive",
    "project": "helix-playground",
    "plugins": [
        {
            "id": "franklin-library",
            "title": "Library",
            "environments": [
                "edit"
            ],
            "isPalette": true,
            "paletteRect": "top: auto; bottom: 20px; left: 50px; height: 398px; width: 360px;",
            "url": "/library/library?suppressFrame=true",
            "includePaths": [
                "**.docx**"
            ]
        }
    ]
}
```

https://rum-admin--helix-website--adobe.aem.live/tools/rum/admin/orgs.html

**Comment by rofe** [comment]
> 2. The sidekick config call on the helix website does not return a mountpoint which we are also not expecting.

We are, at least when adding projects (since #157): https://github.com/adobe/aem-sidekick/blob/main/src/extension/project.js#L264-L266

For transient projects, we should also add support for `contentSourceUrl` in `SiteStore.initConfig()`.
