### ISSUE TITLE
A Breaking Change - Plugin iframes are Destroyed

### ISSUE THREAD

**Issue by slitviachenko** [adobe/aem-sidekick#186]
### Expected Behaviour
Plugins aren't reloaded (corresponding iframes aren't destroyed) each time I close a plugin and reopen it later, allowing state preservation.

### Actual Behaviour
In the old Sidekick, opened plugins aren’t reloaded (corresponding iframes aren’t destroyed) when closing and reopening, allowing state preservation. However, in the new Sidekick, plugins are reloaded (corresponding iframes are destroyed) each time I close a plugin and reopen it later, causing state loss.

#### Steps to Reproduce
1. Create a palette plugin.
2. Click on a plugin button to open it; observe that the plugin is loaded in a new iframe.
3. Close the plugin; observe that the corresponding plugin iframe is deleted.
4. Click on the plugin button again; observe that it is loaded again from scratch in a new iframe, thus losing all previous data/state.

**Comment by rofe** [comment]
I acknowledge that this is a breaking change. However, I believe it's cleaner - and expected from a user POV - to start fresh every time a user opens a plugin. You could still manage state using `localStorage` or `sessionStorage`.
