### ISSUE TITLE
layout issue with bulk operations

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/aem-sidekick#198]
when selecting multiple items i am getting the following layout...

<img width="735" alt="image" src="https://github.com/adobe/aem-sidekick/assets/5289336/4e2bf3c3-cb95-4e53-a19c-33fffe85e98f">

**Comment by rofe** [comment]
@dylandepass could this be related to your recent styling updates?

**Comment by dylandepass** [comment]
Interesting.. I'm not able to reproduce with the released version of Sidekick Next Gen. What about you @rofe?

![Screenshot 2024-06-30 at 1 32 05 PM](https://github.com/adobe/aem-sidekick/assets/3231084/db9b6aba-b75e-4979-a42a-21c265da9b7c)

@davidnuescheler What project did you see this on? Any reproductions steps you can provide.

**Comment by rofe** [comment]
No, I haven't been able to reproduce it either.

**Comment by rofe** [comment]
Saw this on @tripodsan's screen yesterday, so I guess it's still a thing...

**Comment by rofe** [comment]
Should be fixed with #301, feel free to reopen if it persists.
