### ISSUE TITLE
Extensible Source Support

### ISSUE THREAD

**Issue by auniverseaway** [adobe/aem-sidekick#244]
### Expected Behaviour
Sidekick can take a configuration to provide an editor / source link format.

### Actual Behaviour
Sidekick currently only supports Microsoft SharePoint & Google Drive.

### Reproduce Scenario (including but not limited to)
Use DA or XWalk.

#### Steps to Reproduce
Open Sidekick on:
**DA:** https://main--da-tutorial--da-sites.hlx.page/demo
**XWalk:**  https://main--aem-demo-project--mhaack.aem.page/topics/

...and notice there is no edit or "open in ..." button.
<img width="660" alt="Screenshot 2024-09-06 at 10 18 33 AM" src="https://github.com/user-attachments/assets/0eb9a2bd-b123-4728-b0d1-3106324d6687">

#### Platform and Version
1.30.1

### Proposal
```json
{
  "project": "My DA Project",
  "source": {
    "name": "Document Authoring",
    "format": "https://da.live/edit#/{{org}}/{{repo}}{{pathname}}"
  },
}
```
<img width="715" alt="Screenshot 2024-09-06 at 10 11 26 AM" src="https://github.com/user-attachments/assets/5e020f96-e4ec-492f-ab04-1b3931e830d8">

The above is on the flexible side to support different variations. I cannot speak for other patterns, but DA could also work with a simple pathname:

```json
{
  "project": "My DA Project",
  "source": {
    "name": "Document Authoring",
    "format": "https://da.live/edit#/da-sites/da-tutorial{{pathname}}"
  },
}
```

@mhaack @buuhuu it would be nice if you could share your thoughts from an XWalk / UE perspective.

**Comment by buuhuu** [comment]
For Xwalk, we would need to know the content source url, as these are single tenant for AEM. That would be the url from the fstab.yaml or the content source configuration in the config service.

{{contentSource}}/{{path}}?cmd=open

example

https://author-p123-e1234.adobeaemcloud.com/bin/franklin.delivery/owner/repo/main/path/to/page?cmd=open

There are some edge cases for which that won't work. For example for paths that contain special characters in AEM, that are replacd by `-` by the admin service. We sent a x-content-source-location header while publishing to mitigate this.
