### ISSUE TITLE
JS API to get access to logged-in information

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/aem-sidekick#259]
it would be great to have access from `*.aem.page` and `*.aem.live` sites to see which projects/sites a user is logged into in sidekick to tweak tooling experience accordingly. i am not sure if this is an event based interface and what level of information we would like to expose initially (eg. expiry time)  and possibly what scope (eg. just within the same org if not `labs.` or `tools.`)

**Comment by rofe** [comment]
We changed to org-level log in, so we don't keep the site info.

**Comment by tripodsan** [comment]
> We changed to org-level log in, so we don't keep the site info.

but transient site tokens are per-site. so if a user is logged into `org/site1` and then later accesses `org/site2`, he needs to login again.

**Comment by rofe** [comment]
> but transient site tokens are per-site

Correct. I was referring to admin login tokens. I think that from a tooling perspective, site tokens aren't relevant.
