### ISSUE TITLE
Dark Mode Disabled Buttons are Hard to See

### ISSUE THREAD

**Issue by meganthecoder** [adobe/aem-sidekick#356]
### Expected Behaviour

I would expect disabled buttons to still be readable even though they are less noticeable (lower contrast) than active buttons.

### Actual Behaviour

In dark mode, the disabled button is practically unreadable. The text color is extremely close to the background color.

<img width="769" alt="Screenshot 2024-11-11 at 7 14 32 PM" src="https://github.com/user-attachments/assets/103d8f28-46c3-4914-ac30-3d97d05e55c2">

#### Steps to Reproduce

1. Switch Chrome to Dark Mode
2. Go to https://main--milo--adobecom.hlx.page/drafts/methomas/send-to-caas
3. Open the sidekick and view the Publish button

#### Platform and Version

AEM Sidekick version 7.0.2. Chrome 130 on Mac

#### Sample Code that illustrates the problem

https://github.com/adobecom/milo/pull/3107

**Comment by meganthecoder** [comment]
Thank you!

**Comment by rofe** [comment]
You are welcome & thanks for reporting!
