### ISSUE TITLE
Folder name and file name are not separated in error about illegal characters

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/aem-sidekick#375]
### Expected Behaviour
File path in error is clear, example: /folder/filename

### Actual Behaviour
Folder name is not separated from file name in 'This file contains illegal characters' error, example: /folderfilename

#### Steps to Reproduce
1. Install extension
2. Add project to extension
3. Select file with  !@# characters in name
4. Click on Preview button on action bar

#### Platform and Version
Chrome 131.0.6778.86
Sidekick v7.1.2

![7 1 2](https://github.com/user-attachments/assets/b8a8da56-ef8f-4ced-a1b8-979fda4a5a39)

**Comment by rofe** [comment]
@Adobe-G11N-I18N-L10N-Team Can you please specify the content source used (Google Drive or SharePoint) as well as the exact folder and filenames used in the test?

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
@rofe Issue is reproducible on Sharepoint and Google Drive. In both cases folder name is "folder" and filename is "filename!"
![7 1 2 unloc google](https://github.com/user-attachments/assets/3a345fef-ef52-4ec4-9b87-adacc552cd98)
![7 1 2 unloc sharepoint](https://github.com/user-attachments/assets/c0b1a061-7c6e-4cf6-ae53-63402407eff0)

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is fixed, verified on 7.1.3
![7 1 3 1](https://github.com/user-attachments/assets/efe7a525-8ab7-4bc0-a0a1-9f63f414ca35)
