### ISSUE TITLE
[Google Drive] Empty error on previewing Excel / Word file in Editor

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/aem-sidekick#380]
### Expected Behaviour
Error message is present on action bar when user tries to preview Excel file from editor

### Actual Behaviour
Error on action bar has no message

#### Steps to Reproduce
1. Install extension
2. Add project to extension
3. Upload and edit Excel or Word file
4. On action bar click on Preview button

#### Platform and Version
Chrome 131.0.6778.86
Sidekick 7.1.2

![7 1 2](https://github.com/user-attachments/assets/53becc11-9f0b-4e62-aab4-bb0ce654fe39)

**Comment by rofe** [comment]
@Adobe-G11N-I18N-L10N-Team this is an Excel file which is not a supported format in Google Drive. I could reproduce the empty error message.

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is fixed, verified on 7.1.3
![7 1 3 1](https://github.com/user-attachments/assets/5808cde8-a6f9-4ea1-b48f-fc6b8a254277)
![7 1 3 2](https://github.com/user-attachments/assets/91aa557c-bf7f-42fb-a5be-914e04a522e7)
