### ISSUE TITLE
[i18n] Confusing error on previewing file with CCJK / cyrillic / arabic characters in name

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/aem-sidekick#386]
### Expected Behaviour
Error clearly explains why preview of file with CCJK / cyrillic / arabic in name failed, most likely because characters are not allowed in filename. 
Error is displayed in Details when file is previewed in bulk

### Actual Behaviour
'Source document does not exist, preview generation failed." error is displayed on previewing existing document with CCJK / cyrillic / arabic characters in name. 
When the file is previewed in bulk, no error is displayed in Details, but when user opens preview URL, error is displayed.

#### Steps to Reproduce
1. Install extension
2. Add project to extension
3. Create document with CCJK / cyrillic / arabic characters in name (テスト, русский, شقشلاهؤ) 
4. Select document > Preview
5. Select document with name 'test' and document with CCJK / cyrillic / arabic > Preview > Preview

#### Platform and Version
Chrome 131.0.6778.86
Sidekick 7.1.2

![7 1 2](https://github.com/user-attachments/assets/dce3f8a2-9220-4c67-ad1c-aa5ebf939614)
![7 1 2 cyrillic](https://github.com/user-attachments/assets/b99311e0-9000-473a-9373-dc6d5cb09972)
![7 1 2 arabic](https://github.com/user-attachments/assets/7dc01ee2-99a3-43f5-b6bc-79b9b96b8331)

https://github.com/user-attachments/assets/a644c1b5-21f3-4419-a484-c41b486a4d26

**Comment by rofe** [comment]
Looks like the filename of the document with only CCJK characters is reduced to just `/`, which would be equivalent to an `index` document in the same folder.

**Comment by Adobe-G11N-I18N-L10N-Team** [comment]
Issue is fixed, verified on 7.1.3
![7 1 3 1](https://github.com/user-attachments/assets/9c22acaa-4d4d-4d79-b0c6-6d8d59b29e7e)
![7 1 3 2](https://github.com/user-attachments/assets/eeb1f7c2-b2f5-4782-8326-63c1022affe5)
